### ISSUE TITLE
add SonarQube to docker-compose

### ISSUE THREAD

**Issue by BertKoor** [Ordina-JTech/fordintysa-ci#13]

**Comment by johanvogelzang** [comment]
Added Sonarqube to docker-compose. 
Still issue left with accessing the app icw Nginx.

**Comment by BertKoor** [comment]
Thanks for the preparations, got it working now:

- copied the `sonar.properties` file out of the container
- changed `sonar.web.context=/sonarqube` 
- `sonarqube/Dockerfile` created that copies our own properties file into the container
- changed the `docker-compose` to build instead of directly use the image
- lined to the correct URL in `index.html`
