### ISSUE TITLE
fix Jenkins reverse proxy settings

### ISSUE THREAD

**Issue by BertKoor** [Ordina-JTech/fordintysa-ci#14]
Jenkins complains about the reverse proxy is not all that well.
Maybe it needs an extra header in `homepage/default.conf` ?

**Comment by srenkens** [comment]
Could not find a solution to this problem. The Chrome console shows a 404 error causing this warning. Since Jenkins is running fine this is a low priority issue at the momen

**Comment by srenkens** [comment]
Closing since it's not an issue at the moment

**Comment by BertKoor** [comment]
squashed with commit [d49f0](https://github.com/Ordina-JTech/fordintysa-ci/commit/d49f0ef64c7a0ec9280a1a8580faf796d444f407)
