### ISSUE TITLE
how to deploy the final app?

### ISSUE THREAD

**Issue by BertKoor** [Ordina-JTech/fordintysa-ci#15]
Ideas:

 * unpack to a prepared servlet container
 * unpack to Jenkins/UserContent
 * spin up a new Docker container

**Comment by srenkens** [comment]
Compose enriched with a Tomcat service to deploy the artifact to.
Jenkins container will get an volume mapped in at `/tomcat-webapps-volume` that mappes to the `/usr/local/tomcat/webapps` location in the tomcat container.

**Comment by srenkens** [comment]
Deploy kan in Jenkins gedaan worden met `cp ./target/*.war /tomcat-webapps-volume/app.war`
