### ISSUE TITLE
create a VirtualBox ISO

### ISSUE THREAD

**Issue by BertKoor** [Ordina-JTech/fordintysa-ci#3]
This ISO will be distributed on USB sticks. 
Based on Boot2Docker? Should include docker-compose and reasonable shell with working backspace.
Save it in a state where all Docker images are already pulled.
Probably 2 CPU cores & 4GB RAMwill be enough.

It should be accompanied with a .pdf containing instructions how to get it up & running, up to:
```
./open.sh
```

**Comment by BertKoor** [comment]
Docker images that need to be pulled:

  - nginx:1.11.9 
  - jacekkow/gitblit:v1.8.0 
  - jenkins:2.32.2 
  - docker.bintray.io/jfrog/artifactory-oss:4.15.0 
  - tomcat:7.0.75-jre8 

docker pull nginx:1.11.9
docker pull jacekkow/gitblit:v1.8.0
docker pull jenkins:2.32.2
docker pull docker.bintray.io/jfrog/artifactory-oss:4.15.0
docker pull tomcat:7.0.75-jre8

**Comment by BertKoor** [comment]
Question posted at Docker forum:
https://forums.docker.com/t/how-to-distribute-docker-machine-provisioned-with-some-images/28455?u=bertkoor

**Comment by srenkens** [comment]
Graag testen door deze zip te downloaden en de README te volgen die opgenomen is in de zip:
www.kareldestoute.nl/fordintysa-ci.zip

**Comment by BertKoor** [comment]
op de VM moet ook Instellingen - Opslag nog eens doorlopen worden, bevat nl absolute paden naar jou schijf D:\Data\VM's.

boot2docker.iso is makkelijk te fixen, maar de schijf niet:

Het is niet gelukt harde schijf bestand C:\Workspace\Ordina\fordintysa-ci\stick\fordintysa-ci\disk.vmdk te openen.

> Cannot register the hard disk 'C:\Workspace\Ordina\fordintysa-ci\stick\fordintysa-ci\disk.vmdk' {29148f30-84fe-47ea-8ca1-c85139d1989f} **because a hard disk 'D:\data\VM's\fordintysa-ci\disk.vmdk' with UUID {29148f30-84fe-47ea-8ca1-c85139d1989f} already exists.**

Ga ff kijken of ik die kan lokaliseren...

**Comment by srenkens** [comment]
Die heb ik ook gehad. niet verwacht dat deze bij jou ook zou optreden...

Mijn workaround was het volgende:
c:\Program\ Files\Oracle\VirtualBox\VBoxManage internalcommands sethduuid disk.vmdk

**Comment by srenkens** [comment]
Het volgende heb ik gedaan om van die absolute paden af te komen.
1. De file `fordintysa-ci.vbox` een niveau hoger gezet op hetzelfde niveau als `disk.vmdk` en `boot2docker.iso`
2. De file `fordintysa-ci.vbox`  gewijzigd door de absolute paden te verwijderen en alleen de filenames te laten staan. 
```
<HardDisk uuid="{29148f30-84fe-47ea-8ca1-c85139d1989f}" location="disk.vmdk" format="VMDK" type="Normal"/>
en
<Image uuid="{9d7ee7e6-5ecf-410b-95b9-9399d7f71a72}" location="boot2docker.iso"/>
```

3. Toevoegen in virtualbox

**Comment by BertKoor** [comment]
`docker image ls` werkt!

> docker@fordintysa-ci:~$ docker image ls
> REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
> tomcat                                    7.0.75-jre8         29b0d21967c4        7 days ago          333 MB
> jenkins                                   2.32.2              ee06af673de2        7 days ago          713 MB
> docker.bintray.io/jfrog/artifactory-oss   4.15.0              7e62030682f1        2 months ago        448 MB
> jacekkow/gitblit                          v1.8.0              a15410b04624        7 months ago        489 MB

Mis alleen nog wel de nginx:1.11.9 image

**Comment by BertKoor** [comment]
Ik ben zo stoer geweest om `fordintysa-ci.vbox` te editten.
Correctie van pad was genoeg, daarna geen klacht gehad over niet-unieke disk.

Ik ga ook ff kijken of je daarin relatieve paden mag gebruiken...

**Comment by BertKoor** [comment]
het kan trouwens ook zonder putty (scheelt wat config hoofdpijn)
gewoon de VM opstarten, je bent dan root.
> exit
>
> Core Linux
> fordintysa-ci login: docker
> Password: tcuser

dan mis je alleen wel cut&paste en een scroll buffer, maar enige dat ze nog hoeven te doen is
> cd /mnt/sda1/fordintysa-ci
> sudo ./open.sh sesame.yml

**Comment by srenkens** [comment]
Zonder putty en direct via VirualBox heeft wel enkele nadelen:
- Knippen en plakken werkt niet
- Mensen die niet bekend zijn met VirtualBox kunnen opgesloten raken in het VirtualBox window omdat ze niet weten dat ze er met de rechter ctrl toets uit moeten.
Persoonlijk zou ik lekker via putty werken.

**Comment by BertKoor** [comment]
accoord

**Comment by srenkens** [comment]
Nieuwe zip online: http://www.kareldestoute.nl/fordintysa-ci-v1318.zip
- git pull
- nginx image gepulled
- jenkins image alvast gebouwd

**Comment by BertKoor** [comment]
Beter !!! prima werk, Sebas...
