### ISSUE TITLE
Artifactory hijacks / (slash - the homepage)

### ISSUE THREAD

**Issue by BertKoor** [Ordina-JTech/fordintysa-ci#4]
Formerly `http://${ip}/` showed `/index.html` with reveal.js content.
Since Artifactory is added to docker-compose, it hijacks the `/` location and does a forward to it's own loading page. Somehow in `homepage/default.conf` (the nginx config) the first location is not first preferred. Puzzles me, since only location `/artifactory` should forward to Artifactory.

NB:  `http://${ip}/index.html` still works...

**Comment by srenkens** [comment]
Seems fixed, cannot reproduce

**Comment by BertKoor** [comment]
not reproducable
