### ISSUE TITLE
Jenkins data persistence in container

### ISSUE THREAD

**Issue by BertKoor** [Ordina-JTech/fordintysa-ci#7]
Noticed the GitBlit container remembers it's state and survives docker-compose stop & up. Can be purged with `docker-compose rm -f` btw.
Can we do the same thing with Jenkins? Now it restarts completely blank...

**Comment by srenkens** [comment]
Non-issue. Zie: https://github.com/jenkinsci/docker/blob/fd794015787ba07d84a7c8d4c625652e648408c5/Dockerfile

De regel `VOLUME /var/jenkins_home` zorgt ervoor dat build history e.d. in bewaard blijven.
